swagger: '2.0'
info:
  description: CS 3733 Group Project API
  version: 1.0.0
  title: YouthfulIndiscretionAPI

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: users
  description: End user calls

paths:
  /playlist:
    get:
      tags:
      - users
      summary: request a list of all playlists
      operationId: getPlaylists
      description: |
        Returns all playlists in library with all categorized video segments
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: playlists retrieved
    post:
      tags:
      - users
      summary: request to create a playlist
      operationId: requestCreatePlaylist
      description: Adds an item to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: PlaylistCreateRequest
        description: Create a playlist to add to library
        required: false
        schema:
          $ref: '#/definitions/PlaylistCreateRequest'
      responses:
        201:
          description: playlist created
        400:
          description: invalid input, object invalid
        409:
          description: duplicate playlist
  /playlistdelete:
    post:
      tags:
      - users
      summary: request to delete a playlist
      operationId: requestDeletePlaylist
      #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: PlaylistDeleteRequest
        description: Delete a playlist from library
        required: false
        schema:
          $ref: '#/definitions/PlaylistDeleteRequest'
      responses:
        200:
          description: playlist deleted
        409:
          description: playlist not found
  /videosegment:
    get:
      tags:
      - users
      - admins
      summary: request a list of all video segments
      operationId: getVideoSegments
      #description:
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: list of video segments returned
    post:
      tags:
      - users
      summary: request to create a new video segment
      operationId: requestCreateVideoSegment
      #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: VideoSegmentCreateRequest
        description: Create a video segment to add to library
        required: false
        schema:
          $ref: '#/definitions/VideoSegmentCreateRequest'
      responses:
        200:
          description: video segment created
        400:
          description: input invalid
        409:
          description: duplicate video segment
  /videosegmentdelete:
    post:
      tags:
      - users
      - admins
      summary: request to delete a video segment
      operationId: requestDeleteVideoSegment
     #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: VideoSegmentRequest
        description: Delete a video segment from library
        required: false
        schema:
          $ref: '#/definitions/VideoSegmentDeleteRequest'
      responses:
        200:
          description: video segment deleted
        400:
          description: invalid input
        409:
          description: unable to deletevideo segment
  /videosegmentappend:
    post:
      tags:
      - users
      summary: request to append a video segment to a playlist
      operationId: requestAppendVideoSegment
      #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: VideoSegmentAppendRequest
        description: Append a video segment to add to a playlist
        required: false
        schema:
          $ref: '#/definitions/VideoSegmentAppendRequest'
      responses:
        200:
          description: video segment appended
        400:
          description: invalid input
        409:
          description: unable to append video segment
  /videosegmentremove:
    post:
      tags:
      - users
      summary: request to remove a video segment from a playlist
      operationId: requestRemoveVideoSegment
      #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: VideoSegmentDeleteRequest
        description: Create a playlist to add to library
        required: false
        schema:
          $ref: '#/definitions/VideoSegmentDeleteRequest'
      responses:
        200:
          description: video segment removed from playlist
        400:
          description: invalid input
        409:
          description: unable to remove video segment
  /videosegmentsearch:
    post:
      tags:
      - users
      summary: request a list of video segments matching search criteria
      operationId: searchVideoSegments
      #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: VideoSegmentSearchRequest
        description: Create a playlist to add to library
        required: false
        schema:
          $ref: '#/definitions/VideoSegmentSearchRequest'
      responses:
        200:
          description: list of matching video segments returned
        400:
          description: invalid input
  /videosegmentmark:
    post:
      tags:
      - admins
      summary: request to mark a video segment
      operationId: requestMarkVideoSegment
      #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: VideoSegmentMarkRequest
        description: Marks a Video Segment
        required: false
        schema:
          $ref: '#/definitions/VideoSegmentMarkRequest'
      responses:
        200:
          description: video segment (un)marked
        400:
          description: invalid input
        409:
          description: unable to mark video segment
  /site:
    get:
      tags:
      - admins
      summary: request a list of all sites
      operationId: getSites
      #description:
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: list of sites returned
    post:
      tags:
      - admins
      summary: request to add a site
      operationId: requestCreateSite
      #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: SiteCreateRequest
        description: Create a playlist to add to library
        required: false
        schema:
          $ref: '#/definitions/SiteCreateRequest'
      responses: 
        200:
          description: site added
        400:
          description: invalid input
        409: #not sure if we need this one
          description: duplicate site
  /siteremove:
    post:
      tags:
      - admins
      summary: request to remove a site
      operationId: requestRemoveSite
     #description:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: SiteRemoveRequest
        description: Create a playlist to add to library
        required: false
        schema:
          $ref: '#/definitions/SiteRemoveRequest'
      responses:
        200:
          description: site removed from list
        400:
          description: invalid input
        409:
          description: unable to remove site
definitions:
  PlaylistCreateRequest: # not sure if we would even have anything in here
    required:
    - name
    properties:
      name:
        type: string
        example: Playlist 1
  PlaylistDeleteRequest:
    required:
    - id
    properties:
      id:
        type: object
        example: 0x00000000000000001
  VideoSegmentCreateRequest:
    type: object
    required:
    - fileName
    - character
    - phrase
    properties:
      fileName:
        type: string
        example: vid1.ogg
      character:
        type: string
        example: McCoy
      phrase:
        type: string
        example: Captain!
  VideoSegmentDeleteRequest:
    type: object
    required:
    - id
    properties:
      id:
        type: object
        example: 0x00053200f00da0ef023
  VideoSegmentAppendRequest:
    type: object
    required:
    - vidid
    - playlistid
    properties:
      vidid:
        type: object
      playlistid:
        type: object
  VideoSegmentSearchRequest:
    type: object
    required:
    - character
    - phrase
    properties:
      character:
        type: string
        example: Spock
      phrase:
        type: string
        example: I can't
  VideoSegmentMarkRequest:
    type: object
    required:
    - id
    properties:
      id:
        type: object
        example: 0x00053200f00da0ef023
  SiteCreateRequest:
    type: object
    required:
    - id
    - url
    properties:
      id:
        type: object
      url:
        type: string
  SiteRemoveRequest:
    type: object
    required:
    - id
    properties:
      id:
        type: object
        example: 0x00053200f00da0ef023
    
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /YouthfulIndiscretion/YouthfulIndiscretionAPI/1.0.0
schemes:
 - https